name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Image with API Key
        run: |
          docker build . -t my-app:latest --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Save Docker Image to file (optional, for publishing)
        run: |
          docker save my-app:latest > my-app.tar